### PR TITLE
Upgrade nodejs to v16.3

### PR DESCRIPTION
**Pull request by Pooja-08**
Upgrade nodejs version from v14.16 to v16.3

### CODE REVIEW

**Review by swati1102 — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by anoopjb — CHANGES_REQUESTED** [review]
We may need to bump the nodejs version in `.travis.yml` . So that Travis runs the unit tests with the matching node version.
A related PR is #1285

**Comment by Pooja-08** [comment]
> We may need to bump the nodejs version in `.travis.yml` . So that Travis runs the unit tests with the matching node version.
> A related PR is #1285

Thanks @anoopjb . Added the changes to the same commit. Ran the unit tests and they all passed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by anoopjb — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Pull request merged**
