### PR TITLE
Install rxjs as peer dependency of hystrixjs

### PR DESCRIPTION
**Pull request by anoopjb**
The `hystrixjs` library used in the http clients require `rxjs` as [peer dependency](https://blog.bitsrc.io/understanding-peer-dependencies-in-javascript-dbdb4ab5a7be). The peer dependencies needs to installed along with the requesting library. Hence rearranging the installation of the `rxjs`.

The multi line `yarn workspaces focus` was overwriting the dependencies. Hence it is advisable to keep a single `yarn workspaces focus` installation in a Dockerfile.

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Review by jintusebastian — APPROVED** [review]
LGTM

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Pull request merged**
