### PR TITLE
Update axios from 0.20.0 to 0.21.4

### PR DESCRIPTION
**Pull request by visargsoneji**
NGPBUG-162966

### CODE REVIEW

**Review by saud89 — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by anoopjb — APPROVED** [review]

**Pull request merged**
