### PR TITLE
Interoperator Improvements suggested by CFforK8S

### PR DESCRIPTION
**Pull request by vivekzhere**
- For the leader cluster make kubeconfig secret optional
- Propagate the error to the CRs
- Trim space from rendered objects

Feature: HCPCFS-2841

### CODE REVIEW

**Review by subhankarc — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Pull request merged**
