### PR TITLE
Update readme to use custom settings.yml

### PR DESCRIPTION
**Pull request by muralisc**
Issue: #161

### CODE REVIEW

**Comment by muralisc** [comment]
@subhankarc 
But this will make updating setting.yml very cumbersome.
https://www.atlassian.com/git/tutorials/gitignore#ignoring-a-previously-committed
go ahead with this ?

**Comment by jagadish-kb** [comment]
@subhankarc @muralisc making settings.yml file as part of .gitignore list only makes the whole proceess cumbersome and also it does not guarantee accidental checkin of sensitive info. My recommendation is that every member of the team religiously follows the existing guideline of using the settings file of the format 'my-settings.yml'. 
The other option which can be done in the long run is to extract all sensitive info into a seperate file called `credentials.yml` and then we can gitignore this file. Properties related to credentials are something that will be only added once in a while and sample attrib names can be added and force commit for this ignore file can be done occassionally.

**Comment by muralisc** [comment]
https://github.com/cloudfoundry-incubator/service-fabrik-broker/pull/167
In addition to above removed the default settings.yml from service-fabrik-broker so the environment variable has to be set for local development.

**Comment by kamath-prasad** [comment]
@subhankarc  :  Can you pls review/approve this PR as well ?

**Comment by subhankarc** [comment]
Hi @jagadish-kb ,

Just to force the developers to use custom settings, also suggested @mualisc to remove the default settings yaml code. 

I think this should make it complete.

**Pull request merged**
