### PR TITLE
Bump node from 16.3-alpine3.13 to 16.8-alpine3.14

### PR DESCRIPTION
**Pull request by anoopjb**

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Review by Pooja-08 — APPROVED** [review]

**Pull request merged**
