### PR TITLE
upgrading lodash to 4.17.20

### PR DESCRIPTION
**Pull request by jayeshjk**

### CODE REVIEW

**Review by vivekzhere — APPROVED** [review]

**Review by subhankarc — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by subhankarc — APPROVED** [review]

**Pull request merged**
