### PR TITLE
Lazy Replication of SFService and SFPlan

### PR DESCRIPTION
**Pull request by vivekzhere**
- Replicate these as part of Instance Replicator
- Remove SFService Replicator

Fetaure: HCPCFS-2505

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by jayeshjk — APPROVED** [review]
LGTM

**Comment by vivekzhere** [comment]
Rebased with master

**Review by subhankarc — APPROVED** [review]

**Pull request merged**
