### PR TITLE
Configure replicator worker count

### PR DESCRIPTION
**Pull request by anoopjb**
- configure service binding replicator worker count using `BindingWorkerCount`
- configure service instance replicator worker count using `InstanceWorkerCount`

### CODE REVIEW

**Review by vivekzhere — APPROVED** [review]

**Review by vivekzhere — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Pull request merged**
