### PR TITLE
update golang.org/x/text to v0.3.7

### PR DESCRIPTION
**Pull request by jintusebastian**

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Review by anoopjb — APPROVED** [review]
LGTM

**Pull request merged**
