### PR TITLE
Bump helm version from v3.7.2 to v3.8.0

### PR DESCRIPTION
**Pull request by Pooja-08**

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n is succeeded.

**Review by anoopjb — APPROVED** [review]
LGTM 👍

**Pull request merged**
