### PR TITLE
Remove dependency of cert in mTLS disabled quota app

### PR DESCRIPTION
**Pull request by anoopjb**
Same as #1570 
Changes for the 0.22.0 branch

Bug: NGPBUG-181544

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by Pooja-08 — APPROVED** [review]

**Pull request merged**
