### PR TITLE
increase upper bound on file fetched from iaas store

### PR DESCRIPTION
**Pull request by jayeshjk**

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Review by subhankarc — APPROVED** [review]

**Review by vivekzhere — APPROVED** [review]

**Pull request merged**
