### PR TITLE
Remove unused rxjs & express_jwt libraries from osb_broker & quota_app.

### PR DESCRIPTION
**Pull request by Pooja-08**

### CODE REVIEW

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n+n+n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n failed.

**Review by anoopjb — APPROVED** [review]

**Pull request merged**
