### PR TITLE
Update kubernetes client to latest

### PR DESCRIPTION
**Pull request by vivekzhere**
- Avoid indirect dep to node-forge
- Update to k8s 1.18

### CODE REVIEW

**Review by jayeshjk — COMMENTED** [review]
Seems some UTs are failing travis build

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Review by subhankarc — APPROVED** [review]

**Pull request merged**
