### PR TITLE
Deployments with '0000' network segment index don't get updated

### PR DESCRIPTION
**Pull request by amitmalav**

### CODE REVIEW

**Comment by sauravmndl** [comment]
Add UT.

**Comment by amitmalav** [comment]
@sauravmndl UT is already present for this scenario. IMO this if condition shouldn't even be present here. Kept it just so that we don't have any unintended consequences.

**Comment by sauravmndl** [comment]
> @sauravmndl UT is already present for this scenario. IMO this if condition shouldn't even be present here. Kept it just so that we don't have any unintended consequences.

Code coverage went down. That is why asked. Otherwise looks fine.

**Comment by amitmalav** [comment]
@sauravmndl Those 2 files are not related to the changes. Coverage flickers in those 2 files :)

**Comment by sauravmndl** [comment]
@amitmalav Ok. Perfect ! Thanks for clarifying. We can merge the PR then.

**Pull request merged**
