### PR TITLE
fixing typo in instances_retrievable flag

### PR DESCRIPTION
**Pull request by jayeshjk**
It needs to be `instances_retrievable`
Ref: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-instance

### CODE REVIEW

**Review by vivekzhere — COMMENTED** [review]
Does the SFService Crds also require the change? CRD has `bindingRetrievable` and `instanceRetrievable` which when transformed becomes  `binding_retrievable` and `instance_retrievable`


https://github.com/cloudfoundry-incubator/service-fabrik-broker/blob/master/helm-charts/interoperator/crds/sfservice.yaml#L48

**Review by swati1102 — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-2 is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n-1 is succeeded.

**Review by vivekzhere — APPROVED** [review]

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Comment by vinaybheri** [comment]
Validation on k8s cluster: n is succeeded.

**Pull request merged**
